spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_USERNAME}
    password: ${LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql


  jpa:
    hibernate:
      ddl-auto: update   # 처음엔 create / update 쓰고, 나중엔 validate로 바꾸면 좋음
    show-sql: true       # 콘솔에 SQL 보이게
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true   # ⭐⭐ 이거 중요
logging:
  level:
    org.hibernate.SQL: debug
jwt:
  secret: "${JWT_SECRET_KEY}"
  access-token-validity-ms: 36000000
